if (DEFINED ENV{SYSTEMC_VERSION})
    set (SYSTEMC_VERSION $ENV{SYSTEMC_VERSION})
else()
    message(FATAL_ERROR "You need to set the SYSTEMC_VERSION environment variable!\nIE:\nexport SYSTEMC_VERSION=2.3.3\n")
endif()
if (DEFINED ENV{SYSTEMC_HOME})
    set (SYSTEMC_HOME $ENV{SYSTEMC_HOME})
else()
    message(FATAL_ERROR "You need to set the SYSTEMC_HOME environment variable!")
endif()
include_directories("${SYSTEMC_HOME}/include")
include_directories("${SYSTEMC_HOME}/include/sysc")
include_directories("${SYSTEMC_HOME}/include/tlm_core")
include_directories("${SYSTEMC_HOME}/include/tlm_utils")
link_directories("${SYSTEMC_HOME}/lib")
